export const projects = [
  {
    name: "NumPay",
    desc: "Global money transfers using just phone numbers - instant, free, and no app needed.",
    lang: "ReactJS + TailwindCSS",
    link: "https://numpay-six.vercel.app",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "NumPay x402",
    desc: "Seamless money transfers using phone numbers with privacy built-in and KYC by Assure DeFi.",
    lang: "Next.js TailwindCSS",
    link: "https://numpay-new-landing.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Magmar Landing",
    desc: "ERC-4337 toolkit for RWA and DePIN with gasless transactions, social login, and multichain support.",
    lang: "Next.js + TailwindCSS",
    link: "https://magmar-landing-page.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Magmar Wallet",
    desc: "Smart Wallet simplifying crypto transactions and asset management securely.",
    lang: "Next.js + Web3 + TailwindCSS",
    link: "https://magmar-new-frontend.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Sral Engineering Ltd",
    desc: "Reliable electrical and instrumentation services for Nigeria's industrial needs.",
    lang: "Node.js + Express.js + MongoDB + ReactJS + TailwindCSS",
    link: "https://sralengineeringltd.com/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Whisper",
    desc: "Decentralized privacy messaging with encrypted wallet-based chats, asset transfers, and voice messaging.",
    lang: "Next.js + Web3 + TailwindCSS",
    link: "https://whisper-landing-page.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Scupie",
    desc: "Official artist universe featuring music drops, luxury merch, NFTs, and immersive experiences.",
    lang: "Next.js + TailwindCSS + Web3 Integrations",
    link: "https://scupie-main.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Chimly",
    desc: "AI-powered productivity platform automating repetitive tasks and streamlining team workflows.",
    lang: "Next.js + Node.js + Express.js + MongoDB",
    link: "https://chimly.ai/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Blockgram",
    desc: "Blockchain-powered Telegram client for crypto transfers, AI, and secure chats.",
    lang: "Next.js + TailwindCSS",
    link: "https://blitzgramm.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Blockgram Landing Page",
    desc: "First blockchain-powered Telegram client with crypto, AI, and digital identity features.",
    lang: "ReactJS + TailwindCSS",
    link: "https://blockgram-landing.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Path Robotics Clone",
    desc: "Global reputation infrastructure giving robots secure digital identity and measurable reliability.",
    lang: "React Router Framework + TailwindCSS + GSAP",
    link: "https://path-robotics-clone.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Pixite",
    desc: "Decentralized climate tech platform for sustainability allies.",
    lang: "Next.js + TailwindCSS",
    link: "https://pixite-omega.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "CodeIDE",
    desc: "Browser-based IDE with AI understanding your entire codebase - no installations needed.",
    lang: "GSAP + ReactJS + TailwindCSS",
    link: "https://codeide-landing.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Grass IO Clone",
    desc: "Clone of Grass IO decentralized network platform.",
    lang: "Next.js + Framer Motion + TailwindCSS",
    link: "https://grass-io-clone.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Ondevi Clone",
    desc: "Universal operating system for robots with modular SDK for cross-compatible development.",
    lang: "React Router Framework + TailwindCSS",
    link: "https://ondevi-clone.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Delta Exchange",
    desc: "Decentralized trading DApp for crypto derivatives and perpetual contracts.",
    lang: "Next.js + Web3 Integrations + TailwindCSS",
    link: "https://delta-exchange-jade.vercel.app/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Electric Keke",
    desc: "Eco-friendly ride-booking platform for electric Keke rides.",
    lang: "ReactJS + TailwindCSS + Axios + Map API",
    link: "https://electric-keke-frontend.vercel.app/",
    github: "https://github.com/heycalebszn/Kobodrop",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Xdegen",
    desc: "A safer way to trade degen/meme coins.",
    lang: "Next.js + ReactJS + TailwindCSS + Typescript + Rust",
    link: "https://xdegen.xyz/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
];
  // {
  //   name: "SBA",
  //   desc: "Get loans and grants for individuals and businesses.",
  //   lang: "PHP + JavaScript + Bootstrap",
  //   link: "https://sbaorg.vercel.app",
  //   github: "https://github.com/heycalebszn",
  // },
  // {
  //   name: "Omorix",
  //   desc: "E-commerce platform.",
  //   lang: "React.js + Node.js + Express.js + PosgreSQL",
  //   link: "https://chimly.ai",
  //   github: "https://github.com/heycalebszn",
  //   preview: "/previews/portscan.jpeg",
  // },
  // {
  //   name: "Bannerly",
  //   desc: "Get social banners for web3 and web2 devs and designers.",
  //   lang: "React.js + Cloudinary + TailwindCSS",
  //   link: "https://bannerly.vercel.app",
  //   github: "https://github.com/heycalebszn/bannerly",
  // },
  // {
  //   name: "Afrovivo Waitlist",
  //   desc: "Seamless waitlist system for a Ghanaian-based company.",
  //   lang: "Next.js + Node.js + TailwindCSS",
  //   link: "https://afrovivo-waitlist-coral.vercel.app/",
  //   github: "https://github.com/heycalebszn/afrovivo-waitlist",
  // },
  // {
  //   name: "Rewrap",
  //   desc: "NPM package for quick Vite + TailwindCSS project setup.",
  //   lang: "NodeJS + Chalk + Execa + Prompts",
  //   link: "https://www.npmjs.com/package/rewrap-vitejs-tailwind",
  //   github: "https://github.com/heycalebszn/Rewrap-",
  // },
  // {
  //   name: "Baba AI",
  //   desc: "Pidgin chatbot that won a hackathon for engaging conversations.",
  //   lang: "ReactJS + API + NodeJS + Express + TailwindCSS + MongoDB",
  //   link: "https://baba-frontend-react-06ac.onrender.com/",
  //   github: "https://github.com/code-clan-g3/baba-frontend-react",
  // },