export const projects = [
  {
    name: "Chimly",
    desc: "Ai-powered task manager.",
    lang: "Next.js + Node.js + Express.js + MongoDB",
    link: "https://chimly.ai",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "Omorix",
    desc: "E-commerce platform.",
    lang: "React.js + Node.js + Express.js + PosgreSQL",
    link: "https://chimly.ai",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  // {
  //   name: "Bannerly",
  //   desc: "Get social banners for web3 and web2 devs and designers.",
  //   lang: "React.js + Cloudinary + TailwindCSS",
  //   link: "https://bannerly.vercel.app",
  //   github: "https://github.com/heycalebszn/bannerly",
  // },
  {
    name: "Xdegen",
    desc: "A safer way to trade degen/meme coins.",
    lang: "Next.js + ReactJS + TailwindCSS + Typescript + Rust",
    link: "https://xdegen.xyz/",
    github: "https://github.com/heycalebszn",
    preview: "/previews/portscan.jpeg",
  },
  {
    name: "SBA",
    desc: "Get loans and grants for individuals and businesses.",
    lang: "PHP + JavaScript + Bootstrap",
    link: "https://sbaorg.vercel.app",
    github: "https://github.com/heycalebszn",
  },
  // {
  //   name: "Afrovivo Waitlist",
  //   desc: "Seamless waitlist system for a Ghanaian-based company.",
  //   lang: "Next.js + Node.js + TailwindCSS",
  //   link: "https://afrovivo-waitlist-coral.vercel.app/",
  //   github: "https://github.com/heycalebszn/afrovivo-waitlist",
  // },
  {
    name: "Electric Keke",
    desc: "Eco-friendly ride-booking platform for electric Keke rides.",
    lang: "ReactJS + TailwindCSS + Axios + Map API",
    link: "https://electric-keke-frontend.vercel.app/",
    github: "https://github.com/heycalebszn/Kobodrop",
    preview: "/previews/portscan.jpeg",
  },
  // {
  //   name: "Rewrap",
  //   desc: "NPM package for quick Vite + TailwindCSS project setup.",
  //   lang: "NodeJS + Chalk + Execa + Prompts",
  //   link: "https://www.npmjs.com/package/rewrap-vitejs-tailwind",
  //   github: "https://github.com/heycalebszn/Rewrap-",
  // },
  // {
  //   name: "Baba AI",
  //   desc: "Pidgin chatbot that won a hackathon for engaging conversations.",
  //   lang: "ReactJS + API + NodeJS + Express + TailwindCSS + MongoDB",
  //   link: "https://baba-frontend-react-06ac.onrender.com/",
  //   github: "https://github.com/code-clan-g3/baba-frontend-react",
  // },
];